name: Pipeline_1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test_CI_CD_PipeLine:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
      - name: checkout the repo
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flake 8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: check code format
        run: |
          # Stop the build i there are any issues detected by flake8
          flake8 . --count --show-source --statistics --max-complexity=10 --max-line-length=150

      - name: set up env file for tests
        run: cat env_files/.env.local > .env

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Run tests
        run: |
          docker exec djangoRest python manage.py makemigrations
          docker exec djangoRest python manage.py migrate
          docker exec djangoRest python manage.py test
          

